//LOCALHOST
###
GET http://localhost:8080/contacts
###
GET http://localhost:8080/contacts/63bdee9f0e4544cbeab7dc71/
### 
GET http://localhost:8080/contacts/63bdee9f0e4544cbeab7dc72
### 
GET http://localhost:8080/contacts/63bdee9f0e4544cbeab7dc73
